
package com.hcl.coe.api.cms.stub;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ContentPort", targetNamespace = "http://www.cms.api.coe.hcl.com/content-ws")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ContentPort {


    /**
     * 
     * @param updateContentRequest
     * @return
     *     returns com.hcl.coe.api.cms.stub.UpdateContentResponse
     */
    @WebMethod
    @WebResult(name = "updateContentResponse", targetNamespace = "http://www.cms.api.coe.hcl.com/content-ws", partName = "updateContentResponse")
    public UpdateContentResponse updateContent(
        @WebParam(name = "updateContentRequest", targetNamespace = "http://www.cms.api.coe.hcl.com/content-ws", partName = "updateContentRequest")
        UpdateContentRequest updateContentRequest);

    /**
     * 
     * @param getContentByPlanIdRequest
     * @return
     *     returns com.hcl.coe.api.cms.stub.GetContentByPlanIdResponse
     */
    @WebMethod
    @WebResult(name = "getContentByPlanIdResponse", targetNamespace = "http://www.cms.api.coe.hcl.com/content-ws", partName = "getContentByPlanIdResponse")
    public GetContentByPlanIdResponse getContentByPlanId(
        @WebParam(name = "getContentByPlanIdRequest", targetNamespace = "http://www.cms.api.coe.hcl.com/content-ws", partName = "getContentByPlanIdRequest")
        GetContentByPlanIdRequest getContentByPlanIdRequest);

    /**
     * 
     * @param deleteContentRequest
     * @return
     *     returns com.hcl.coe.api.cms.stub.DeleteContentResponse
     */
    @WebMethod
    @WebResult(name = "deleteContentResponse", targetNamespace = "http://www.cms.api.coe.hcl.com/content-ws", partName = "deleteContentResponse")
    public DeleteContentResponse deleteContent(
        @WebParam(name = "deleteContentRequest", targetNamespace = "http://www.cms.api.coe.hcl.com/content-ws", partName = "deleteContentRequest")
        DeleteContentRequest deleteContentRequest);

    /**
     * 
     * @param addContentRequest
     * @return
     *     returns com.hcl.coe.api.cms.stub.AddContentResponse
     */
    @WebMethod
    @WebResult(name = "addContentResponse", targetNamespace = "http://www.cms.api.coe.hcl.com/content-ws", partName = "addContentResponse")
    public AddContentResponse addContent(
        @WebParam(name = "addContentRequest", targetNamespace = "http://www.cms.api.coe.hcl.com/content-ws", partName = "addContentRequest")
        AddContentRequest addContentRequest);

}
